import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'English' | 'Hindi' | 'Marathi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  English: {
    'nav.home': 'Home',
    'nav.telemedicine': 'Telemedicine',
    'nav.appointments': 'Appointments',
    'nav.vaccinations': 'Vaccinations',
    'nav.records': 'Health Records',
    'nav.report': 'Report Symptoms',
    'nav.facilities': 'Facilities',
    'nav.map': 'Health Map',
    'nav.announcements': 'Announcements',
    'nav.profile': 'Profile',
    'nav.signout': 'Sign Out',
    'search.placeholder': 'Search doctors, hospitals, records...',
    'dashboard.greeting': 'Hello, Rahul',
    'dashboard.subtitle': 'Manage your health records and appointments',
    'dashboard.report_symptoms': 'Report Symptoms',
    'dashboard.advisory.title': 'Local Health Advisory: Dengue Alert',
    'dashboard.advisory.desc': 'Increased cases of Dengue reported in your area (Ward 4). Please ensure no stagnant water around your home and use mosquito repellents. If you experience high fever, report symptoms immediately.',
    'dashboard.advisory.link': 'Read Guidelines →',
    'dashboard.quick.book': 'Book Appointment',
    'dashboard.quick.lab': 'Lab Reports',
    'dashboard.quick.prescriptions': 'Prescriptions',
    'dashboard.quick.hospital': 'Find Hospital',
    'dashboard.quick.telemedicine': 'Telemedicine',
    'dashboard.quick.vaccinations': 'Vaccinations',
    'dashboard.quick.map': 'Health Map',
    'dashboard.recent_records': 'Recent Health Records',
    'dashboard.view_all': 'View All',
    'dashboard.upcoming_appointments': 'Upcoming Appointments',
    'dashboard.confirmed': 'Confirmed',
    'dashboard.reschedule': 'Reschedule',
    'dashboard.details': 'Details',
    'dashboard.local_worker': 'Your Local Health Worker',
    'dashboard.asha_worker': 'ASHA Worker, Ward 4',
    'dashboard.contact_asha': 'Contact ASHA',
    'dashboard.calling': 'Calling...',
    'telemedicine.title': 'Telemedicine Consultations',
    'telemedicine.subtitle': 'Book video consultations with SMC doctors',
    'telemedicine.search': 'Search doctors by name or specialty...',
    'telemedicine.book': 'Book Consultation',
    'telemedicine.booking': 'Booking...',
    'telemedicine.confirmed': 'Confirmed!',
    'vaccination.title': 'Vaccination Center',
    'vaccination.subtitle': 'Manage immunizations and reminders',
    'vaccination.register': 'Register for Reminders',
    'vaccination.history': 'Vaccination History',
    'facilities.title': 'Nearby Health Facilities',
    'facilities.subtitle': 'Find hospitals, clinics, and pharmacies near you',
    'facilities.search': 'Search facilities by name or location...',
    'facilities.call': 'Call',
    'facilities.directions': 'Directions',
    'map.title': 'City Health Map',
    'map.subtitle': 'View active health advisories and nearby facilities',
    'map.layers': 'Map Layers',
    'map.filter': 'Filter Data',
    'map.advisories': 'Active Advisories',
    'map.advisories.subtitle': 'Based on syndromic surveillance',
    'announcements.title': 'Public Health Announcements',
    'announcements.subtitle': 'Official updates and preventive care information from SMC',
    'announcements.recent': 'Recent Announcements',
    'announcements.preventive': 'Preventive Care',
    'announcements.resources': 'Downloadable Resources',
    'appointments.title': 'My Appointments',
    'appointments.subtitle': 'Manage your upcoming and past doctor visits',
    'appointments.book': 'Book New Appointment',
    'appointments.upcoming': 'Upcoming',
    'appointments.filter': 'Filter:',
    'appointments.all': 'All Types',
    'appointments.inperson': 'In-Person',
    'appointments.tele': 'Teleconsultation',
    'appointments.reschedule': 'Reschedule',
    'appointments.request_sent': 'Request Sent',
    'appointments.join': 'Join Call',
    'appointments.connecting': 'Connecting...',
    'admin.nav.command': 'Command Center',
    'admin.nav.actions': 'AI Action Center',
    'admin.nav.surveillance': 'Disease Surveillance',
    'admin.nav.risk': 'Health Risk Map',
    'admin.nav.workers': 'Field Workers (ASHA)',
    'admin.nav.reports': 'Reports & Analytics',
    'admin.nav.settings': 'Settings',
    'admin.search': 'Search patients, wards, diseases...',
    'admin.signout': 'Sign Out',
    'asha.nav.dashboard': 'My Dashboard',
    'asha.nav.queue': 'Smart Task Queue',
    'asha.nav.report': 'New Survey/Report',
    'asha.nav.community': 'My Community',
    'asha.nav.profile': 'Profile',
    'asha.search': 'Search families, patients...',
    'asha.signout': 'Sign Out',
    'asha.dashboard.welcome': 'Welcome back, Sunita',
    'asha.dashboard.subtitle': 'Here is your daily summary for Ward 4',
    'asha.dashboard.report_emergency': 'Report Emergency',
    'asha.dashboard.families': 'Families Covered',
    'asha.dashboard.tasks': 'Tasks Today',
    'asha.dashboard.pending': 'Pending Follow-ups',
    'asha.dashboard.high_risk': 'High Risk Patients',
    'asha.dashboard.priority': 'Priority Tasks',
    'asha.dashboard.view_queue': 'View Queue',
    'asha.dashboard.quick_actions': 'Quick Actions',
    'asha.dashboard.new_survey': 'New Survey',
    'asha.dashboard.new_survey_desc': 'Start a new household survey',
    'asha.dashboard.report_symptom': 'Report Symptom',
    'asha.dashboard.report_symptom_desc': 'Log a new syndromic case',
    'asha.dashboard.anc': 'ANC Registration',
    'asha.dashboard.anc_desc': 'Register new pregnancy',
    'asha.dashboard.camp': 'Health Camp',
    'asha.dashboard.camp_desc': 'View upcoming camps',
    'asha.queue.title': 'Smart Intervention Queue',
    'asha.queue.subtitle': 'AI-prioritized tasks based on health risk factors',
    'asha.queue.filter': 'Filter',
    'asha.queue.ai_active': 'AI Prioritization Active',
    'asha.queue.ai_desc': 'Tasks are ordered by clinical urgency. Priya Sharma and Rahul Verma have been moved to the top due to missed critical ANC checkup and prolonged fever reports in a known dengue cluster area.',
    'asha.queue.all': 'All Tasks',
    'asha.queue.high': 'High Priority',
    'asha.queue.completed': 'Completed',
    'asha.queue.search': 'Search tasks...',
    'asha.report.title': 'New Survey / Report',
    'asha.report.subtitle': 'Log new health data from the field',
    'asha.report.symptom': 'Symptom Check',
    'asha.report.anc': 'ANC Registration',
    'asha.report.survey': 'Household Survey',
    'asha.report.success': 'Report Submitted Successfully',
    'asha.report.success_desc': 'The data has been synced with the central system.',
    'asha.report.submit_another': 'Submit Another Report',
    'asha.report.patient_name': 'Patient Name',
    'asha.report.age': 'Age',
    'asha.report.location': 'Location / Address',
    'asha.report.symptoms': 'Primary Symptoms',
    'asha.report.notes': 'Additional Notes',
    'asha.report.submit': 'Submit Report',
    'asha.community.title': 'My Community',
    'asha.community.subtitle': 'Manage families and individuals in your assigned area',
    'asha.community.add_family': 'Add Family',
    'asha.community.family_added': 'Family Added',
    'asha.community.search': 'Search families, names, or addresses...',
    'asha.community.family_id': 'Family ID',
    'asha.community.head': 'Head of Family',
    'asha.community.location': 'Location',
    'asha.community.contact': 'Contact',
    'asha.community.risk': 'Risk Level',
    'asha.community.members': 'Members',
    'admin.dashboard.title': 'Command Center Overview',
    'admin.dashboard.subtitle': 'Real-time public health metrics for Solapur City',
    'admin.dashboard.last_7': 'Last 7 Days',
    'admin.dashboard.last_30': 'Last 30 Days',
    'admin.dashboard.this_month': 'This Month',
    'admin.dashboard.generate': 'Generate Report',
    'admin.dashboard.generated': 'Report Generated',
    'admin.dashboard.active_outbreaks': 'Active Outbreaks',
    'admin.dashboard.total_cases': 'Total Cases Reported',
    'admin.dashboard.asha_active': 'ASHA Workers Active',
    'admin.dashboard.interventions': 'Interventions Completed',
    'admin.dashboard.disease_trend': 'Disease Trend Analysis',
    'admin.dashboard.high_risk_wards': 'High Risk Wards',
    'admin.dashboard.view_map': 'View Detailed Map',
    'admin.dashboard.infra_avail': 'Infrastructure Availability',
    'admin.dashboard.manage': 'Manage',
    'admin.dashboard.updating': 'Updating...',
    'admin.dashboard.supply_alerts': 'Supply Chain Alerts',
    'admin.dashboard.order_supplies': 'Order Supplies',
    'admin.dashboard.ordering': 'Ordering...',
    'admin.dashboard.recent_alerts': 'Recent Alerts & Interventions',
    'admin.dashboard.view_all': 'View All',
    'admin.dashboard.alert_type': 'Alert Type',
    'admin.dashboard.location': 'Location',
    'admin.dashboard.severity': 'Severity',
    'admin.dashboard.reported_by': 'Reported By',
    'admin.dashboard.status': 'Status',
    'admin.dashboard.action': 'Action',
    'admin.ai.title': 'AI Action Center',
    'admin.ai.subtitle': 'Smart, prioritized public health interventions generated by AI',
    'admin.ai.reset': 'Reset Demo',
    'admin.ai.refresh': 'Refresh Analysis',
    'admin.ai.refreshing': 'Analyzing...',
    'admin.ai.pending_actions': 'Recommended Interventions',
    'admin.ai.completed_actions': 'Action History',
    'admin.ai.approve': 'Approve & Deploy',
    'admin.ai.dismiss': 'Dismiss',
    'admin.ai.processing': 'Processing...',
    'admin.ai.approved': 'Approved',
    'admin.ai.dismissed': 'Dismissed',
    'admin.ai.all_caught_up': 'All Caught Up!',
    'admin.ai.no_pending': 'No pending AI recommendations at this time.',
    'admin.ai.no_completed': 'No processed actions yet.',
    'admin.ai.priority.critical': 'Critical',
    'admin.ai.priority.high': 'High',
    'admin.ai.priority.medium': 'Medium',
    'admin.ai.population': 'Affected Population',
    'admin.ai.recommendation': 'AI Recommendation',
    'hospital.nav.dashboard': 'Hospital Dashboard',
    'hospital.nav.beds': 'Bed Management',
    'hospital.nav.inventory': 'Inventory & Stock',
    'hospital.nav.billing': 'Billing & Receipts',
    'hospital.nav.profile': 'Hospital Profile',
    'hospital.dashboard.welcome': 'Hospital Operations Center',
    'hospital.dashboard.subtitle': 'Real-time monitoring and resource management',
    'hospital.dashboard.total_beds': 'Total Capacity',
    'hospital.dashboard.available_beds': 'Available Beds',
    'hospital.dashboard.icu_available': 'ICU Available',
    'hospital.dashboard.oxygen_available': 'Oxygen Available',
    'hospital.dashboard.equipment_status': 'Equipment Status',
    'hospital.dashboard.medicine_stock': 'Medicine Stock',
    'hospital.dashboard.vaccine_stock': 'Vaccine Stock',
    'hospital.beds.title': 'Bed Availability Management',
    'hospital.beds.subtitle': 'Update occupancy and track bed types',
    'hospital.beds.general': 'General Beds',
    'hospital.beds.icu': 'ICU Beds',
    'hospital.beds.oxygen': 'Oxygen Beds',
    'hospital.beds.occupied': 'Occupied',
    'hospital.beds.available': 'Available',
    'hospital.beds.update': 'Update Occupancy',
    'hospital.inventory.title': 'Inventory & Stock Monitoring',
    'hospital.inventory.subtitle': 'Manage medical equipment, medicines, and vaccines',
    'hospital.inventory.equipment': 'Medical Equipment',
    'hospital.inventory.medicines': 'Medicines',
    'hospital.inventory.vaccines': 'Vaccines',
    'hospital.inventory.item_name': 'Item Name',
    'hospital.inventory.stock': 'Current Stock',
    'hospital.inventory.status': 'Status',
    'hospital.inventory.actions': 'Actions',
    'hospital.inventory.update_stock': 'Update Stock',
    'hospital.inventory.replenish': 'Request Replenishment',
    'hospital.inventory.flag_shortage': 'Flag Shortage',
    'hospital.billing.title': 'Billing & Receipts',
    'hospital.billing.subtitle': 'Generate and manage patient consultation receipts',
    'hospital.billing.patient_name': 'Patient Name',
    'hospital.billing.amount': 'Amount',
    'hospital.billing.date': 'Date',
    'hospital.billing.download': 'Download Receipt',
    'hospital.billing.generate': 'Generate New Bill',
    'hospital.profile.title': 'Hospital Profile',
    'hospital.profile.subtitle': 'Official contact and facility information',
    'hospital.profile.emergency': 'Emergency Number',
    'hospital.profile.ambulance': 'Ambulance Support',
    'hospital.profile.departments': 'Available Departments',
    'hospital.profile.call': 'Call Hospital',
    'hospital.profile.directions': 'Get Directions',
  },
  Hindi: {
    'nav.home': 'होम',
    'nav.telemedicine': 'टेलीमेडिसिन',
    'nav.appointments': 'अपॉइंटमेंट',
    'nav.vaccinations': 'टीकाकरण',
    'nav.records': 'स्वास्थ्य रिकॉर्ड',
    'nav.report': 'लक्षण दर्ज करें',
    'nav.facilities': 'सुविधाएं',
    'nav.map': 'स्वास्थ्य मानचित्र',
    'nav.announcements': 'घोषणाएं',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.signout': 'साइन आउट',
    'search.placeholder': 'डॉक्टर, अस्पताल, रिकॉर्ड खोजें...',
    'dashboard.greeting': 'नमस्ते, राहुल',
    'dashboard.subtitle': 'अपने स्वास्थ्य रिकॉर्ड और अपॉइंटमेंट प्रबंधित करें',
    'dashboard.report_symptoms': 'लक्षण दर्ज करें',
    'dashboard.advisory.title': 'स्थानीय स्वास्थ्य सलाह: डेंगू अलर्ट',
    'dashboard.advisory.desc': 'आपके क्षेत्र (वार्ड 4) में डेंगू के मामले बढ़े हैं। कृपया सुनिश्चित करें कि आपके घर के आसपास पानी जमा न हो और मच्छर भगाने वाले उत्पादों का उपयोग करें। यदि आपको तेज बुखार है, तो तुरंत लक्षण दर्ज करें।',
    'dashboard.advisory.link': 'दिशानिर्देश पढ़ें →',
    'dashboard.quick.book': 'अपॉइंटमेंट बुक करें',
    'dashboard.quick.lab': 'लैब रिपोर्ट',
    'dashboard.quick.prescriptions': 'पर्चे',
    'dashboard.quick.hospital': 'अस्पताल खोजें',
    'dashboard.quick.telemedicine': 'टेलीमेडिसिन',
    'dashboard.quick.vaccinations': 'टीकाकरण',
    'dashboard.quick.map': 'स्वास्थ्य मानचित्र',
    'dashboard.recent_records': 'हाल के स्वास्थ्य रिकॉर्ड',
    'dashboard.view_all': 'सभी देखें',
    'dashboard.upcoming_appointments': 'आगामी अपॉइंटमेंट',
    'dashboard.confirmed': 'पुष्टि की गई',
    'dashboard.reschedule': 'पुनर्निर्धारित करें',
    'dashboard.details': 'विवरण',
    'dashboard.local_worker': 'आपका स्थानीय स्वास्थ्य कार्यकर्ता',
    'dashboard.asha_worker': 'आशा कार्यकर्ता, वार्ड 4',
    'dashboard.contact_asha': 'आशा से संपर्क करें',
    'dashboard.calling': 'कॉल कर रहे हैं...',
    'telemedicine.title': 'टेलीमेडिसिन परामर्श',
    'telemedicine.subtitle': 'SMC डॉक्टरों के साथ वीडियो परामर्श बुक करें',
    'telemedicine.search': 'नाम या विशेषज्ञता से डॉक्टरों को खोजें...',
    'telemedicine.book': 'परामर्श बुक करें',
    'telemedicine.booking': 'बुक कर रहे हैं...',
    'telemedicine.confirmed': 'पुष्टि की गई!',
    'vaccination.title': 'टीकाकरण केंद्र',
    'vaccination.subtitle': 'टीकाकरण और अनुस्मारक प्रबंधित करें',
    'vaccination.register': 'अनुस्मारक के लिए पंजीकरण करें',
    'vaccination.history': 'टीकाकरण इतिहास',
    'facilities.title': 'आसपास की स्वास्थ्य सुविधाएं',
    'facilities.subtitle': 'अपने आस-पास अस्पताल, क्लीनिक और फार्मेसियों का पता लगाएं',
    'facilities.search': 'नाम या स्थान से सुविधाएं खोजें...',
    'facilities.call': 'कॉल करें',
    'facilities.directions': 'दिशा-निर्देश',
    'map.title': 'शहर स्वास्थ्य मानचित्र',
    'map.subtitle': 'सक्रिय स्वास्थ्य सलाह और आस-पास की सुविधाएं देखें',
    'map.layers': 'मानचित्र परतें',
    'map.filter': 'डेटा फ़िल्टर करें',
    'map.advisories': 'सक्रिय सलाह',
    'map.advisories.subtitle': 'सिंड्रोमिक निगरानी के आधार पर',
    'announcements.title': 'सार्वजनिक स्वास्थ्य घोषणाएं',
    'announcements.subtitle': 'SMC से आधिकारिक अपडेट और निवारक देखभाल जानकारी',
    'announcements.recent': 'हाल की घोषणाएं',
    'announcements.preventive': 'निवारक देखभाल',
    'announcements.resources': 'डाउनलोड करने योग्य संसाधन',
    'appointments.title': 'मेरे अपॉइंटमेंट',
    'appointments.subtitle': 'अपने आगामी और पिछले डॉक्टर के दौरे प्रबंधित करें',
    'appointments.book': 'नया अपॉइंटमेंट बुक करें',
    'appointments.upcoming': 'आगामी',
    'appointments.filter': 'फ़िल्टर:',
    'appointments.all': 'सभी प्रकार',
    'appointments.inperson': 'व्यक्तिगत रूप से',
    'appointments.tele': 'टेलीकंसल्टेशन',
    'appointments.reschedule': 'पुनर्निर्धारित करें',
    'appointments.request_sent': 'अनुरोध भेजा गया',
    'appointments.join': 'कॉल में शामिल हों',
    'appointments.connecting': 'जुड़ रहे हैं...',
    'admin.nav.command': 'कमांड सेंटर',
    'admin.nav.actions': 'एआई एक्शन सेंटर',
    'admin.nav.surveillance': 'रोग निगरानी',
    'admin.nav.risk': 'स्वास्थ्य जोखिम मानचित्र',
    'admin.nav.workers': 'फील्ड वर्कर्स (आशा)',
    'admin.nav.reports': 'रिपोर्ट और एनालिटिक्स',
    'admin.nav.settings': 'सेटिंग्स',
    'admin.search': 'मरीजों, वार्डों, बीमारियों की खोज करें...',
    'admin.signout': 'साइन आउट',
    'asha.nav.dashboard': 'मेरा डैशबोर्ड',
    'asha.nav.queue': 'स्मार्ट टास्क कतार',
    'asha.nav.report': 'नया सर्वेक्षण/रिपोर्ट',
    'asha.nav.community': 'मेरा समुदाय',
    'asha.nav.profile': 'प्रोफ़ाइल',
    'asha.search': 'परिवारों, मरीजों की खोज करें...',
    'asha.signout': 'साइन आउट',
    'asha.dashboard.welcome': 'वापसी पर स्वागत है, सुनीता',
    'asha.dashboard.subtitle': 'यहाँ वार्ड 4 के लिए आपका दैनिक सारांश है',
    'asha.dashboard.report_emergency': 'आपातकाल की रिपोर्ट करें',
    'asha.dashboard.families': 'कवर किए गए परिवार',
    'asha.dashboard.tasks': 'आज के कार्य',
    'asha.dashboard.pending': 'लंबित अनुवर्ती',
    'asha.dashboard.high_risk': 'उच्च जोखिम वाले मरीज',
    'asha.dashboard.priority': 'प्राथमिकता वाले कार्य',
    'asha.dashboard.view_queue': 'कतार देखें',
    'asha.dashboard.quick_actions': 'त्वरित कार्रवाई',
    'asha.dashboard.new_survey': 'नया सर्वेक्षण',
    'asha.dashboard.new_survey_desc': 'एक नया घरेलू सर्वेक्षण शुरू करें',
    'asha.dashboard.report_symptom': 'लक्षण की रिपोर्ट करें',
    'asha.dashboard.report_symptom_desc': 'एक नया सिंड्रोमिक मामला दर्ज करें',
    'asha.dashboard.anc': 'एएनसी पंजीकरण',
    'asha.dashboard.anc_desc': 'नई गर्भावस्था दर्ज करें',
    'asha.dashboard.camp': 'स्वास्थ्य शिविर',
    'asha.dashboard.camp_desc': 'आगामी शिविर देखें',
    'asha.queue.title': 'स्मार्ट हस्तक्षेप कतार',
    'asha.queue.subtitle': 'स्वास्थ्य जोखिम कारकों के आधार पर एआई-प्राथमिकता वाले कार्य',
    'asha.queue.filter': 'फ़िल्टर',
    'asha.queue.ai_active': 'एआई प्राथमिकता सक्रिय',
    'asha.queue.ai_desc': 'कार्यों को नैदानिक ​​तात्कालिकता द्वारा आदेश दिया जाता है। ज्ञात डेंगू क्लस्टर क्षेत्र में छूटे हुए महत्वपूर्ण एएनसी चेकअप और लंबे समय तक बुखार की रिपोर्ट के कारण प्रिया शर्मा और राहुल वर्मा को शीर्ष पर ले जाया गया है।',
    'asha.queue.all': 'सभी कार्य',
    'asha.queue.high': 'उच्च प्राथमिकता',
    'asha.queue.completed': 'पूरा हुआ',
    'asha.queue.search': 'कार्य खोजें...',
    'asha.report.title': 'नया सर्वेक्षण / रिपोर्ट',
    'asha.report.subtitle': 'क्षेत्र से नया स्वास्थ्य डेटा लॉग करें',
    'asha.report.symptom': 'लक्षण की जाँच',
    'asha.report.anc': 'एएनसी पंजीकरण',
    'asha.report.survey': 'घरेलू सर्वेक्षण',
    'asha.report.success': 'रिपोर्ट सफलतापूर्वक सबमिट की गई',
    'asha.report.success_desc': 'डेटा को केंद्रीय प्रणाली के साथ समन्वयित किया गया है।',
    'asha.report.submit_another': 'एक और रिपोर्ट सबमिट करें',
    'asha.report.patient_name': 'मरीज का नाम',
    'asha.report.age': 'आयु',
    'asha.report.location': 'स्थान / पता',
    'asha.report.symptoms': 'प्राथमिक लक्षण',
    'asha.report.notes': 'अतिरिक्त नोट्स',
    'asha.report.submit': 'रिपोर्ट सबमिट करें',
    'asha.community.title': 'मेरा समुदाय',
    'asha.community.subtitle': 'अपने निर्धारित क्षेत्र में परिवारों और व्यक्तियों का प्रबंधन करें',
    'asha.community.add_family': 'परिवार जोड़ें',
    'asha.community.family_added': 'परिवार जोड़ा गया',
    'asha.community.search': 'परिवारों, नामों या पतों को खोजें...',
    'asha.community.family_id': 'परिवार आईडी',
    'asha.community.head': 'परिवार का मुखिया',
    'asha.community.location': 'स्थान',
    'asha.community.contact': 'संपर्क',
    'asha.community.risk': 'जोखिम स्तर',
    'asha.community.members': 'सदस्य',
    'admin.dashboard.title': 'कमांड सेंटर अवलोकन',
    'admin.dashboard.subtitle': 'सोलापुर शहर के लिए वास्तविक समय सार्वजनिक स्वास्थ्य मेट्रिक्स',
    'admin.dashboard.last_7': 'पिछले 7 दिन',
    'admin.dashboard.last_30': 'पिछले 30 दिन',
    'admin.dashboard.this_month': 'इस महीने',
    'admin.dashboard.generate': 'रिपोर्ट जनरेट करें',
    'admin.dashboard.generated': 'रिपोर्ट जनरेट की गई',
    'admin.dashboard.active_outbreaks': 'सक्रिय प्रकोप',
    'admin.dashboard.total_cases': 'कुल मामले दर्ज',
    'admin.dashboard.asha_active': 'आशा कार्यकर्ता सक्रिय',
    'admin.dashboard.interventions': 'हस्तक्षेप पूरे हुए',
    'admin.dashboard.disease_trend': 'रोग प्रवृत्ति विश्लेषण',
    'admin.dashboard.high_risk_wards': 'उच्च जोखिम वाले वार्ड',
    'admin.dashboard.view_map': 'विस्तृत मानचित्र देखें',
    'admin.dashboard.infra_avail': 'बुनियादी ढांचे की उपलब्धता',
    'admin.dashboard.manage': 'प्रबंधित करें',
    'admin.dashboard.updating': 'अपडेट हो रहा है...',
    'admin.dashboard.supply_alerts': 'आपूर्ति श्रृंखला अलर्ट',
    'admin.dashboard.order_supplies': 'आपूर्ति का आदेश दें',
    'admin.dashboard.ordering': 'आदेश दिया जा रहा है...',
    'admin.dashboard.recent_alerts': 'हाल के अलर्ट और हस्तक्षेप',
    'admin.dashboard.view_all': 'सभी देखें',
    'admin.dashboard.alert_type': 'अलर्ट प्रकार',
    'admin.dashboard.location': 'स्थान',
    'admin.dashboard.severity': 'गंभीरता',
    'admin.dashboard.reported_by': 'द्वारा रिपोर्ट किया गया',
    'admin.dashboard.status': 'स्थिति',
    'admin.dashboard.action': 'कार्रवाई',
    'admin.ai.title': 'एआई एक्शन सेंटर',
    'admin.ai.subtitle': 'एआई द्वारा उत्पन्न स्मार्ट, प्राथमिकता वाले सार्वजनिक स्वास्थ्य हस्तक्षेप',
    'admin.ai.reset': 'डेमो रीसेट करें',
    'admin.ai.refresh': 'विश्लेषण ताज़ा करें',
    'admin.ai.refreshing': 'विश्लेषण हो रहा है...',
    'admin.ai.pending_actions': 'अनुशंसित हस्तक्षेप',
    'admin.ai.completed_actions': 'कार्रवाई इतिहास',
    'admin.ai.approve': 'मंजूरी दें और तैनात करें',
    'admin.ai.dismiss': 'खारिज करें',
    'admin.ai.processing': 'प्रसंस्करण...',
    'admin.ai.approved': 'मंजूर',
    'admin.ai.dismissed': 'खारिज',
    'admin.ai.all_caught_up': 'सब हो गया!',
    'admin.ai.no_pending': 'इस समय कोई लंबित एआई सिफारिश नहीं है।',
    'admin.ai.no_completed': 'अभी तक कोई संसाधित कार्रवाई नहीं।',
    'admin.ai.priority.critical': 'गंभीर',
    'admin.ai.priority.high': 'उच्च',
    'admin.ai.priority.medium': 'मध्यम',
    'admin.ai.population': 'प्रभावित जनसंख्या',
    'admin.ai.recommendation': 'एआई सिफारिश',
    'hospital.nav.dashboard': 'अस्पताल डैशबोर्ड',
    'hospital.nav.beds': 'बिस्तर प्रबंधन',
    'hospital.nav.inventory': 'इन्वेंटरी और स्टॉक',
    'hospital.nav.billing': 'बिलिंग और रसीदें',
    'hospital.nav.profile': 'अस्पताल प्रोफ़ाइल',
    'hospital.dashboard.welcome': 'अस्पताल संचालन केंद्र',
    'hospital.dashboard.subtitle': 'वास्तविक समय की निगरानी और संसाधन प्रबंधन',
    'hospital.dashboard.total_beds': 'कुल क्षमता',
    'hospital.dashboard.available_beds': 'उपलब्ध बिस्तर',
    'hospital.dashboard.icu_available': 'आईसीयू उपलब्ध',
    'hospital.dashboard.oxygen_available': 'ऑक्सीजन उपलब्ध',
    'hospital.dashboard.equipment_status': 'उपकरण की स्थिति',
    'hospital.dashboard.medicine_stock': 'दवा का स्टॉक',
    'hospital.dashboard.vaccine_stock': 'टीका स्टॉक',
    'hospital.beds.title': 'बिस्तर उपलब्धता प्रबंधन',
    'hospital.beds.subtitle': 'अधिभोग अपडेट करें और बिस्तर के प्रकारों को ट्रैक करें',
    'hospital.beds.general': 'सामान्य बिस्तर',
    'hospital.beds.icu': 'आईसीयू बिस्तर',
    'hospital.beds.oxygen': 'ऑक्सीजन बिस्तर',
    'hospital.beds.occupied': 'अधिकृत',
    'hospital.beds.available': 'उपलब्ध',
    'hospital.beds.update': 'अधिभोग अपडेट करें',
    'hospital.inventory.title': 'इन्वेंटरी और स्टॉक निगरानी',
    'hospital.inventory.subtitle': 'चिकित्सा उपकरण, दवाओं और टीकों का प्रबंधन करें',
    'hospital.inventory.equipment': 'चिकित्सा उपकरण',
    'hospital.inventory.medicines': 'दवाएं',
    'hospital.inventory.vaccines': 'टीके',
    'hospital.inventory.item_name': 'वस्तु का नाम',
    'hospital.inventory.stock': 'वर्तमान स्टॉक',
    'hospital.inventory.status': 'स्थिति',
    'hospital.inventory.actions': 'कार्रवाई',
    'hospital.inventory.update_stock': 'स्टॉक अपडेट करें',
    'hospital.inventory.replenish': 'पुनर्पूर्ति का अनुरोध करें',
    'hospital.inventory.flag_shortage': 'कमी को चिह्नित करें',
    'hospital.billing.title': 'बिलिंग और रसीदें',
    'hospital.billing.subtitle': 'रोगी परामर्श रसीदें उत्पन्न और प्रबंधित करें',
    'hospital.billing.patient_name': 'रोगी का नाम',
    'hospital.billing.amount': 'राशि',
    'hospital.billing.date': 'दिनांक',
    'hospital.billing.download': 'रसीद डाउनलोड करें',
    'hospital.billing.generate': 'नया बिल जनरेट करें',
    'hospital.profile.title': 'अस्पताल प्रोफ़ाइल',
    'hospital.profile.subtitle': 'आधिकारिक संपर्क और सुविधा की जानकारी',
    'hospital.profile.emergency': 'आपातकालीन नंबर',
    'hospital.profile.ambulance': 'एम्बुलेंस सहायता',
    'hospital.profile.departments': 'उपलब्ध विभाग',
    'hospital.profile.call': 'अस्पताल को कॉल करें',
    'hospital.profile.directions': 'दिशा-निर्देश प्राप्त करें',
  },
  Marathi: {
    'nav.home': 'मुख्यपृष्ठ',
    'nav.telemedicine': 'टेलीमेडिसिन',
    'nav.appointments': 'अपॉइंटमेंट',
    'nav.vaccinations': 'लसीकरण',
    'nav.records': 'आरोग्य नोंदी',
    'nav.report': 'लक्षणे नोंदवा',
    'nav.facilities': 'सुविधा',
    'nav.map': 'आरोग्य नकाशा',
    'nav.announcements': 'घोषणा',
    'nav.profile': 'प्रोफाइल',
    'nav.signout': 'साइन आउट',
    'search.placeholder': 'डॉक्टर, रुग्णालये, नोंदी शोधा...',
    'dashboard.greeting': 'नमस्कार, राहुल',
    'dashboard.subtitle': 'तुमच्या आरोग्य नोंदी आणि अपॉइंटमेंट व्यवस्थापित करा',
    'dashboard.report_symptoms': 'लक्षणे नोंदवा',
    'dashboard.advisory.title': 'स्थानिक आरोग्य सल्ला: डेंग्यू अलर्ट',
    'dashboard.advisory.desc': 'तुमच्या भागात (प्रभाग 4) डेंग्यूच्या रुग्णांमध्ये वाढ झाली आहे. कृपया तुमच्या घराजवळ पाणी साचू देऊ नका आणि डास प्रतिबंधक वापरा. तुम्हाला तीव्र ताप असल्यास, त्वरित लक्षणे नोंदवा.',
    'dashboard.advisory.link': 'मार्गदर्शक तत्त्वे वाचा →',
    'dashboard.quick.book': 'अपॉइंटमेंट बुक करा',
    'dashboard.quick.lab': 'लॅब रिपोर्ट',
    'dashboard.quick.prescriptions': 'प्रिस्क्रिप्शन',
    'dashboard.quick.hospital': 'रुग्णालय शोधा',
    'dashboard.quick.telemedicine': 'टेलीमेडिसिन',
    'dashboard.quick.vaccinations': 'लसीकरण',
    'dashboard.quick.map': 'आरोग्य नकाशा',
    'dashboard.recent_records': 'अलीकडील आरोग्य नोंदी',
    'dashboard.view_all': 'सर्व पहा',
    'dashboard.upcoming_appointments': 'आगामी अपॉइंटमेंट',
    'dashboard.confirmed': 'निश्चित',
    'dashboard.reschedule': 'पुन्हा शेड्यूल करा',
    'dashboard.details': 'तपशील',
    'dashboard.local_worker': 'तुमचा स्थानिक आरोग्य कार्यकर्ता',
    'dashboard.asha_worker': 'आशा कार्यकर्ता, प्रभाग 4',
    'dashboard.contact_asha': 'आशाशी संपर्क साधा',
    'dashboard.calling': 'कॉल करत आहे...',
    'telemedicine.title': 'टेलीमेडिसिन सल्लामसलत',
    'telemedicine.subtitle': 'SMC डॉक्टरांसोबत व्हिडिओ सल्लामसलत बुक करा',
    'telemedicine.search': 'नाव किंवा वैशिष्ट्यानुसार डॉक्टर शोधा...',
    'telemedicine.book': 'सल्लामसलत बुक करा',
    'telemedicine.booking': 'बुक करत आहे...',
    'telemedicine.confirmed': 'निश्चित!',
    'vaccination.title': 'लसीकरण केंद्र',
    'vaccination.subtitle': 'लसीकरण आणि स्मरणपत्रे व्यवस्थापित करा',
    'vaccination.register': 'स्मरणपत्रांसाठी नोंदणी करा',
    'vaccination.history': 'लसीकरण इतिहास',
    'facilities.title': 'जवळपासच्या आरोग्य सुविधा',
    'facilities.subtitle': 'तुमच्या जवळची रुग्णालये, दवाखाने आणि फार्मसी शोधा',
    'facilities.search': 'नाव किंवा ठिकाणानुसार सुविधा शोधा...',
    'facilities.call': 'कॉल करा',
    'facilities.directions': 'दिशा',
    'map.title': 'शहर आरोग्य नकाशा',
    'map.subtitle': 'सक्रिय आरोग्य सल्ला आणि जवळपासच्या सुविधा पहा',
    'map.layers': 'नकाशा स्तर',
    'map.filter': 'डेटा फिल्टर करा',
    'map.advisories': 'सक्रिय सल्ला',
    'map.advisories.subtitle': 'सिंड्रोमिक पाळत ठेवण्यावर आधारित',
    'announcements.title': 'सार्वजनिक आरोग्य घोषणा',
    'announcements.subtitle': 'SMC कडून अधिकृत अद्यतने आणि प्रतिबंधात्मक काळजी माहिती',
    'announcements.recent': 'अलीकडील घोषणा',
    'announcements.preventive': 'प्रतिबंधात्मक काळजी',
    'announcements.resources': 'डाउनलोड करण्यायोग्य संसाधने',
    'appointments.title': 'माझे अपॉइंटमेंट',
    'appointments.subtitle': 'तुमच्या आगामी आणि मागील डॉक्टरांच्या भेटी व्यवस्थापित करा',
    'appointments.book': 'नवीन अपॉइंटमेंट बुक करा',
    'appointments.upcoming': 'आगामी',
    'appointments.filter': 'फिल्टर:',
    'appointments.all': 'सर्व प्रकार',
    'appointments.inperson': 'प्रत्यक्ष',
    'appointments.tele': 'टेलीकन्सल्टेशन',
    'appointments.reschedule': 'पुन्हा शेड्यूल करा',
    'appointments.request_sent': 'विनंती पाठवली',
    'appointments.join': 'कॉलमध्ये सामील व्हा',
    'appointments.connecting': 'कनेक्ट करत आहे...',
    'admin.nav.command': 'कमांड सेंटर',
    'admin.nav.actions': 'एआय ॲक्शन सेंटर',
    'admin.nav.surveillance': 'रोग पाळत ठेवणे',
    'admin.nav.risk': 'आरोग्य जोखीम नकाशा',
    'admin.nav.workers': 'फील्ड वर्कर्स (आशा)',
    'admin.nav.reports': 'अहवाल आणि विश्लेषण',
    'admin.nav.settings': 'सेटिंग्ज',
    'admin.search': 'रुग्ण, प्रभाग, आजार शोधा...',
    'admin.signout': 'साइन आउट करा',
    'asha.nav.dashboard': 'माझे डॅशबोर्ड',
    'asha.nav.queue': 'स्मार्ट टास्क रांग',
    'asha.nav.report': 'नवीन सर्वेक्षण/अहवाल',
    'asha.nav.community': 'माझा समुदाय',
    'asha.nav.profile': 'प्रोफाइल',
    'asha.search': 'कुटुंबे, रुग्ण शोधा...',
    'asha.signout': 'साइन आउट करा',
    'asha.dashboard.welcome': 'परत स्वागत आहे, सुनीता',
    'asha.dashboard.subtitle': 'येथे प्रभाग 4 साठी तुमचा दैनिक सारांश आहे',
    'asha.dashboard.report_emergency': 'आणीबाणीची नोंद करा',
    'asha.dashboard.families': 'कव्हर केलेली कुटुंबे',
    'asha.dashboard.tasks': 'आजची कामे',
    'asha.dashboard.pending': 'प्रलंबित पाठपुरावा',
    'asha.dashboard.high_risk': 'उच्च जोखीम असलेले रुग्ण',
    'asha.dashboard.priority': 'प्राधान्य कार्ये',
    'asha.dashboard.view_queue': 'रांग पहा',
    'asha.dashboard.quick_actions': 'त्वरित कृती',
    'asha.dashboard.new_survey': 'नवीन सर्वेक्षण',
    'asha.dashboard.new_survey_desc': 'नवीन घरगुती सर्वेक्षण सुरू करा',
    'asha.dashboard.report_symptom': 'लक्षण नोंदवा',
    'asha.dashboard.report_symptom_desc': 'नवीन सिंड्रोमिक केस नोंदवा',
    'asha.dashboard.anc': 'ANC नोंदणी',
    'asha.dashboard.anc_desc': 'नवीन गर्भधारणा नोंदवा',
    'asha.dashboard.camp': 'आरोग्य शिबिर',
    'asha.dashboard.camp_desc': 'आगामी शिबिरे पहा',
    'asha.queue.title': 'स्मार्ट हस्तक्षेप रांग',
    'asha.queue.subtitle': 'आरोग्य जोखीम घटकांवर आधारित एआय-प्राधान्य दिलेली कार्ये',
    'asha.queue.filter': 'फिल्टर',
    'asha.queue.ai_active': 'एआय प्राधान्य सक्रिय',
    'asha.queue.ai_desc': 'कार्ये क्लिनिकल तातडीने ऑर्डर केली जातात. ज्ञात डेंग्यू क्लस्टर क्षेत्रात चुकलेली गंभीर ANC तपासणी आणि दीर्घकाळ तापाच्या अहवालामुळे प्रिया शर्मा आणि राहुल वर्मा यांना शीर्षस्थानी हलवण्यात आले आहे.',
    'asha.queue.all': 'सर्व कार्ये',
    'asha.queue.high': 'उच्च प्राधान्य',
    'asha.queue.completed': 'पूर्ण झाले',
    'asha.queue.search': 'कार्ये शोधा...',
    'asha.report.title': 'नवीन सर्वेक्षण / अहवाल',
    'asha.report.subtitle': 'फील्डमधून नवीन आरोग्य डेटा लॉग करा',
    'asha.report.symptom': 'लक्षण तपासणी',
    'asha.report.anc': 'ANC नोंदणी',
    'asha.report.survey': 'घरगुती सर्वेक्षण',
    'asha.report.success': 'अहवाल यशस्वीरित्या सबमिट केला',
    'asha.report.success_desc': 'डेटा मध्यवर्ती प्रणालीसह समक्रमित केला गेला आहे.',
    'asha.report.submit_another': 'आणखी एक अहवाल सबमिट करा',
    'asha.report.patient_name': 'रुग्णाचे नाव',
    'asha.report.age': 'वय',
    'asha.report.location': 'स्थान / पत्ता',
    'asha.report.symptoms': 'प्राथमिक लक्षणे',
    'asha.report.notes': 'अतिरिक्त नोट्स',
    'asha.report.submit': 'अहवाल सबमिट करा',
    'asha.community.title': 'माझा समुदाय',
    'asha.community.subtitle': 'तुमच्या नियुक्त क्षेत्रातील कुटुंबे आणि व्यक्ती व्यवस्थापित करा',
    'asha.community.add_family': 'कुटुंब जोडा',
    'asha.community.family_added': 'कुटुंब जोडले',
    'asha.community.search': 'कुटुंबे, नावे किंवा पत्ते शोधा...',
    'asha.community.family_id': 'कुटुंब आयडी',
    'asha.community.head': 'कुटुंब प्रमुख',
    'asha.community.location': 'स्थान',
    'asha.community.contact': 'संपर्क',
    'asha.community.risk': 'धोका पातळी',
    'asha.community.members': 'सदस्य',
    'admin.dashboard.title': 'कमांड सेंटर विहंगावलोकन',
    'admin.dashboard.subtitle': 'सोलापूर शहरासाठी रिअल-टाइम सार्वजनिक आरोग्य मेट्रिक्स',
    'admin.dashboard.last_7': 'गेले 7 दिवस',
    'admin.dashboard.last_30': 'गेले 30 दिवस',
    'admin.dashboard.this_month': 'या महिन्यात',
    'admin.dashboard.generate': 'अहवाल तयार करा',
    'admin.dashboard.generated': 'अहवाल तयार केला',
    'admin.dashboard.active_outbreaks': 'सक्रिय उद्रेक',
    'admin.dashboard.total_cases': 'एकूण प्रकरणे नोंदवली',
    'admin.dashboard.asha_active': 'आशा कर्मचारी सक्रिय',
    'admin.dashboard.interventions': 'हस्तक्षेप पूर्ण झाले',
    'admin.dashboard.disease_trend': 'रोग कल विश्लेषण',
    'admin.dashboard.high_risk_wards': 'उच्च जोखीम प्रभाग',
    'admin.dashboard.view_map': 'तपशीलवार नकाशा पहा',
    'admin.dashboard.infra_avail': 'पायाभूत सुविधांची उपलब्धता',
    'admin.dashboard.manage': 'व्यवस्थापित करा',
    'admin.dashboard.updating': 'अद्यतनित करत आहे...',
    'admin.dashboard.supply_alerts': 'पुरवठा साखळी सूचना',
    'admin.dashboard.order_supplies': 'पुरवठा ऑर्डर करा',
    'admin.dashboard.ordering': 'ऑर्डर करत आहे...',
    'admin.dashboard.recent_alerts': 'अलीकडील सूचना आणि हस्तक्षेप',
    'admin.dashboard.view_all': 'सर्व पहा',
    'admin.dashboard.alert_type': 'सूचना प्रकार',
    'admin.dashboard.location': 'स्थान',
    'admin.dashboard.severity': 'तीव्रता',
    'admin.dashboard.reported_by': 'द्वारे नोंदवले',
    'admin.dashboard.status': 'स्थिती',
    'admin.dashboard.action': 'कृती',
    'admin.ai.title': 'AI कृती केंद्र',
    'admin.ai.subtitle': 'AI द्वारे व्युत्पन्न स्मार्ट, प्राधान्यकृत सार्वजनिक आरोग्य हस्तक्षेप',
    'admin.ai.reset': 'डेमो रीसेट करा',
    'admin.ai.refresh': 'विश्लेषण रिफ्रेश करा',
    'admin.ai.refreshing': 'विश्लेषण करत आहे...',
    'admin.ai.pending_actions': 'शिफारस केलेले हस्तक्षेप',
    'admin.ai.completed_actions': 'कृती इतिहास',
    'admin.ai.approve': 'मंजूर करा आणि तैनात करा',
    'admin.ai.dismiss': 'डिसमिस करा',
    'admin.ai.processing': 'प्रक्रिया करत आहे...',
    'admin.ai.approved': 'मंजूर',
    'admin.ai.dismissed': 'डिसमिस',
    'admin.ai.all_caught_up': 'सर्व झाले!',
    'admin.ai.no_pending': 'यावेळी कोणतीही प्रलंबित AI शिफारस नाही.',
    'admin.ai.no_completed': 'अद्याप कोणतीही प्रक्रिया केलेली कृती नाही.',
    'admin.ai.priority.critical': 'गंभीर',
    'admin.ai.priority.high': 'उच्च',
    'admin.ai.priority.medium': 'मध्यम',
    'admin.ai.population': 'प्रभावित लोकसंख्या',
    'admin.ai.recommendation': 'AI शिफारस',
    'hospital.nav.dashboard': 'रुग्णालय डॅशबोर्ड',
    'hospital.nav.beds': 'बेड व्यवस्थापन',
    'hospital.nav.inventory': 'इन्वेंटरी आणि स्टॉक',
    'hospital.nav.billing': 'बिलिंग आणि पावत्या',
    'hospital.nav.profile': 'रुग्णालय प्रोफाइल',
    'hospital.dashboard.welcome': 'रुग्णालय ऑपरेशन्स सेंटर',
    'hospital.dashboard.subtitle': 'रिअल-टाइम मॉनिटरिंग आणि संसाधन व्यवस्थापन',
    'hospital.dashboard.total_beds': 'एकूण क्षमता',
    'hospital.dashboard.available_beds': 'उपलब्ध बेड',
    'hospital.dashboard.icu_available': 'ICU उपलब्ध',
    'hospital.dashboard.oxygen_available': 'ऑक्सिजन उपलब्ध',
    'hospital.dashboard.equipment_status': 'उपकरण स्थिती',
    'hospital.dashboard.medicine_stock': 'औषध साठा',
    'hospital.dashboard.vaccine_stock': 'लस साठा',
    'hospital.beds.title': 'बेड उपलब्धता व्यवस्थापन',
    'hospital.beds.subtitle': 'भोगवटा अद्यतनित करा आणि बेड प्रकार ट्रॅक करा',
    'hospital.beds.general': 'सामान्य बेड',
    'hospital.beds.icu': 'ICU बेड',
    'hospital.beds.oxygen': 'ऑक्सिजन बेड',
    'hospital.beds.occupied': 'भरलेले',
    'hospital.beds.available': 'उपलब्ध',
    'hospital.beds.update': 'भोगवटा अद्यतनित करा',
    'hospital.inventory.title': 'इन्वेंटरी आणि स्टॉक मॉनिटरिंग',
    'hospital.inventory.subtitle': 'वैद्यकीय उपकरणे, औषधे आणि लसींचे व्यवस्थापन करा',
    'hospital.inventory.equipment': 'वैद्यकीय उपकरणे',
    'hospital.inventory.medicines': 'औषधे',
    'hospital.inventory.vaccines': 'लसी',
    'hospital.inventory.item_name': 'वस्तूचे नाव',
    'hospital.inventory.stock': 'सध्याचा साठा',
    'hospital.inventory.status': 'स्थिती',
    'hospital.inventory.actions': 'कृती',
    'hospital.inventory.update_stock': 'स्टॉक अपडेट करा',
    'hospital.inventory.replenish': 'पुनर्भरणाची विनंती करा',
    'hospital.inventory.flag_shortage': 'टंचाई नोंदवा',
    'hospital.billing.title': 'बिलिंग आणि पावत्या',
    'hospital.billing.subtitle': 'रुग्ण सल्लामसलत पावत्या तयार करा आणि व्यवस्थापित करा',
    'hospital.billing.patient_name': 'रुग्णाचे नाव',
    'hospital.billing.amount': 'रक्कम',
    'hospital.billing.date': 'तारीख',
    'hospital.billing.download': 'पावती डाउनलोड करा',
    'hospital.billing.generate': 'नवीन बिल तयार करा',
    'hospital.profile.title': 'रुग्णालय प्रोफाइल',
    'hospital.profile.subtitle': 'अधिकृत संपर्क आणि सुविधा माहिती',
    'hospital.profile.emergency': 'आणीबाणी क्रमांक',
    'hospital.profile.ambulance': 'रुग्णवाहिका सहाय्य',
    'hospital.profile.departments': 'उपलब्ध विभाग',
    'hospital.profile.call': 'रुग्णालयाला कॉल करा',
    'hospital.profile.directions': 'दिशा मिळवा',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('English');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
