import { useState } from 'react';
import { Brain, MapPin, Users, AlertTriangle, CheckCircle, ArrowRight, Activity, ShieldAlert, Zap } from 'lucide-react';
import { useLanguage } from '../../contexts/LanguageContext';

interface ActionItem {
  id: string;
  issue: string;
  location: string;
  population: string;
  recommendation: string;
  priority: 'Critical' | 'High' | 'Medium';
  status: 'Pending' | 'Approved' | 'Dismissed';
  icon: any;
}

const initialActions: ActionItem[] = [
  {
    id: 'ACT-001',
    issue: 'Dengue Cluster Detected',
    location: 'Ward 4, Shivaji Nagar',
    population: 'Approx. 450 households at immediate risk',
    recommendation: 'Deploy 3 additional ASHA workers for targeted fogging and source reduction. Issue local SMS advisory.',
    priority: 'Critical',
    status: 'Pending',
    icon: ShieldAlert
  },
  {
    id: 'ACT-002',
    issue: 'Low ANC Registration Rate',
    location: 'Ward 12, Bhavani Peth',
    population: 'Estimated 45 unregistered pregnant women',
    recommendation: 'Schedule a specialized maternal health camp this weekend. Prioritize household visits for W-002.',
    priority: 'High',
    status: 'Pending',
    icon: Activity
  },
  {
    id: 'ACT-003',
    issue: 'Unusual Fever Spike (Syndromic)',
    location: 'Ward 8, Sadar Bazar',
    population: '120 individuals reported symptoms in 48h',
    recommendation: 'Initiate rapid malaria/dengue screening protocol. Alert local PHC to prepare for increased OPD influx.',
    priority: 'High',
    status: 'Pending',
    icon: AlertTriangle
  },
  {
    id: 'ACT-004',
    issue: 'Missed Vaccination Follow-ups',
    location: 'Citywide (Scattered)',
    population: '85 children under 2 years',
    recommendation: 'Generate automated voice calls to parents. Auto-queue follow-up tasks for respective ASHA workers.',
    priority: 'Medium',
    status: 'Pending',
    icon: Users
  }
];

export default function AIActionCenter() {
  const [actions, setActions] = useState<ActionItem[]>(() => {
    const stored = localStorage.getItem('smc_ai_actions');
    return stored ? JSON.parse(stored) : initialActions;
  });
  const [isProcessing, setIsProcessing] = useState<string | null>(null);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const { t } = useLanguage();

  const handleAction = (id: string, newStatus: 'Approved' | 'Dismissed') => {
    setIsProcessing(id);
    // Simulate API call/processing time
    setTimeout(() => {
      const updated = actions.map(action => 
        action.id === id ? { ...action, status: newStatus } : action
      );
      setActions(updated);
      localStorage.setItem('smc_ai_actions', JSON.stringify(updated));
      setIsProcessing(null);
    }, 800);
  };

  const handleRefresh = () => {
    setIsRefreshing(true);
    setTimeout(() => {
      setIsRefreshing(false);
    }, 1500);
  };

  const handleReset = () => {
    setActions(initialActions);
    localStorage.setItem('smc_ai_actions', JSON.stringify(initialActions));
  };

  const pendingActions = actions.filter(a => a.status === 'Pending');
  const completedActions = actions.filter(a => a.status !== 'Pending');

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <Brain className="w-8 h-8 text-indigo-600" />
            AI Action Center
          </h1>
          <p className="text-sm text-slate-500 mt-1">Smart, prioritized public health interventions generated by AI</p>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={handleReset}
            className="bg-white border border-slate-200 text-slate-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-slate-50 transition-colors shadow-sm flex items-center gap-2"
          >
            Reset Demo
          </button>
          <button 
            onClick={handleRefresh}
            disabled={isRefreshing}
            className="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-indigo-700 transition-colors shadow-sm flex items-center gap-2 disabled:opacity-70"
          >
            {isRefreshing ? (
              <>
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                {t('admin.ai.refreshing')}
              </>
            ) : (
              <>
                <Zap className="w-4 h-4" />
                {t('admin.ai.refresh')}
              </>
            )}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Actions List */}
        <div className="lg:col-span-2 space-y-4">
          <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
            {t('admin.ai.pending_actions')}
            <span className="bg-indigo-100 text-indigo-700 py-0.5 px-2.5 rounded-full text-xs font-bold">
              {pendingActions.length}
            </span>
          </h2>

          {pendingActions.length === 0 ? (
            <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-12 text-center">
              <div className="w-16 h-16 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-4">
                <CheckCircle className="w-8 h-8" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-2">{t('admin.ai.all_caught_up')}</h3>
              <p className="text-slate-500">{t('admin.ai.no_pending')}</p>
            </div>
          ) : (
            pendingActions.map((action) => (
              <div key={action.id} className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden transition-all hover:shadow-md">
                <div className={`h-1.5 w-full ${
                  action.priority === 'Critical' ? 'bg-rose-500' : 
                  action.priority === 'High' ? 'bg-amber-500' : 'bg-blue-500'
                }`} />
                <div className="p-6">
                  <div className="flex items-start justify-between gap-4 mb-4">
                    <div className="flex items-start gap-3">
                      <div className={`p-2 rounded-lg mt-1 ${
                        action.priority === 'Critical' ? 'bg-rose-100 text-rose-600' : 
                        action.priority === 'High' ? 'bg-amber-100 text-amber-600' : 'bg-blue-100 text-blue-600'
                      }`}>
                        <action.icon className="w-6 h-6" />
                      </div>
                      <div>
                        <div className="flex items-center gap-2 mb-1">
                          <h3 className="text-lg font-bold text-slate-900">{action.issue}</h3>
                          <span className={`text-xs font-bold px-2 py-0.5 rounded-full border ${
                            action.priority === 'Critical' ? 'bg-rose-50 text-rose-700 border-rose-200' : 
                            action.priority === 'High' ? 'bg-amber-50 text-amber-700 border-amber-200' : 'bg-blue-50 text-blue-700 border-blue-200'
                          }`}>
                            {action.priority === 'Critical' ? t('admin.ai.priority.critical') : action.priority === 'High' ? t('admin.ai.priority.high') : t('admin.ai.priority.medium')}
                          </span>
                        </div>
                        <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-slate-600">
                          <span className="flex items-center gap-1.5">
                            <MapPin className="w-4 h-4 text-slate-400" />
                            {action.location}
                          </span>
                          <span className="flex items-center gap-1.5">
                            <Users className="w-4 h-4 text-slate-400" />
                            {action.population}
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="bg-indigo-50/50 border border-indigo-100 rounded-xl p-4 mb-6">
                    <h4 className="text-xs font-bold text-indigo-900 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                      <Brain className="w-4 h-4" />
                      {t('admin.ai.recommendation')}
                    </h4>
                    <p className="text-sm text-indigo-900 leading-relaxed">
                      {action.recommendation}
                    </p>
                  </div>

                  <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100">
                    <button 
                      onClick={() => handleAction(action.id, 'Dismissed')}
                      disabled={isProcessing === action.id}
                      className="px-4 py-2 text-sm font-medium text-slate-600 hover:text-slate-900 hover:bg-slate-50 rounded-lg transition-colors disabled:opacity-50"
                    >
                      {t('admin.ai.dismiss')}
                    </button>
                    <button 
                      onClick={() => handleAction(action.id, 'Approved')}
                      disabled={isProcessing === action.id}
                      className="bg-indigo-600 text-white px-6 py-2 rounded-lg text-sm font-medium hover:bg-indigo-700 transition-colors shadow-sm flex items-center gap-2 disabled:opacity-70"
                    >
                      {isProcessing === action.id ? (
                        <span className="flex items-center gap-2">
                          <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                          {t('admin.ai.processing')}
                        </span>
                      ) : (
                        <>
                          {t('admin.ai.approve')}
                          <ArrowRight className="w-4 h-4" />
                        </>
                      )}
                    </button>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Sidebar / History */}
        <div className="space-y-6">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
            <h3 className="text-base font-bold text-slate-900 mb-4">How it works</h3>
            <p className="text-sm text-slate-600 mb-4 leading-relaxed">
              The AI Action Center continuously analyzes data from syndromic surveillance, ASHA worker reports, and historical trends to identify emerging health threats.
            </p>
            <ul className="space-y-3 text-sm text-slate-600">
              <li className="flex items-start gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 shrink-0" />
                <span>Predicts outbreaks before they spread</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 shrink-0" />
                <span>Optimizes resource allocation</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 shrink-0" />
                <span>Automates routine follow-ups</span>
              </li>
            </ul>
          </div>

          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
            <h3 className="text-base font-bold text-slate-900 mb-4">Recent Activity</h3>
            <div className="space-y-4">
              {completedActions.length === 0 ? (
                <p className="text-sm text-slate-500 text-center py-4">No recent actions processed.</p>
              ) : (
                completedActions.map(action => (
                  <div key={action.id} className="flex items-start gap-3 pb-4 border-b border-slate-100 last:border-0 last:pb-0">
                    <div className={`mt-0.5 p-1.5 rounded-full ${
                      action.status === 'Approved' ? 'bg-emerald-100 text-emerald-600' : 'bg-slate-100 text-slate-500'
                    }`}>
                      {action.status === 'Approved' ? <CheckCircle className="w-4 h-4" /> : <X className="w-4 h-4" />}
                    </div>
                    <div>
                      <p className="text-sm font-medium text-slate-900 line-clamp-1">{action.issue}</p>
                      <p className="text-xs text-slate-500 mt-0.5">
                        {action.status} • {action.location}
                      </p>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Simple X icon for dismissed state
function X(props: any) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <path d="M18 6 6 18"/><path d="m6 6 12 12"/>
    </svg>
  );
}
